<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net7.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<!-- Referências de pacotes NuGet -->
		<PackageReference Include="Dapper.Contrib" Version="2.0.78" />
		<PackageReference Include="Google.Apis.Gmail.v1" Version="1.68.0.3427" />
		<PackageReference Include="Microsoft.AspNetCore.Http" Version="2.2.2" />
		<PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="7.0.5" />
		<PackageReference Include="NETCore.MailKit" Version="2.1.0" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
		<PackageReference Include="Serilog.Extensions.Logging" Version="7.0.0" />
		<PackageReference Include="Serilog.Sinks.File" Version="5.0.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Financeiro.Solution.Infra.ExternalServices\Financeiro.Solution.Infra.ExternalServices.csproj" />
	</ItemGroup>

</Project>
