name: Sync Pull Request to Azure Boards

on:
  pull_request_target:
    types: [opened, edited, closed]
    branches:
      - master

jobs:
  alert:
    runs-on: ubuntu-latest
    steps:
    - uses: danhellem/github-actions-pr-to-work-item@master
      env:
        ado_token: '${{ secrets.ADO_PERSONAL_ACCESS_TOKEN }}'   
        github_token: '${{ secrets.GH_TOKEN }}'    
        ado_organization: 'ProjetoFinanceiroEstudos'
        ado_project: 'ProjetoFinanceiroEstudos'
        ado_wit: 'TASK' 
        ado_new_state: 'To do '
        ado_active_state: 'in Progress'
        ado_close_state: 'Done'
        ado_area_path: 'ProjetoFinanceiroEstudos'
